---
driver:
  name: lxd_cli
  #public_key_path: "~/.ssh/id_rsa.pub"
  username: root
  password: kitchen

provisioner:
  product_name: chef
  install_strategy: skip # we have the chef client installed
  #require_chef_omnibus: false   # we have the chef client installed !#old way

verifier:
  name: inspec

platforms:
#- name: ubuntu-18.04
#  driver:
#    image: dokken/ubuntu-18.04
#    pid_one_command: /bin/systemd
#    intermediate_instructions:
#      - RUN /usr/bin/apt-get update

- name:  kitchen-ol7

suites:
  - name: default
    run_list: 
      - recipe[fai_linux_baseline::default]
     #- recipe[test_cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

